"""
Django settings for catelogiq project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catelogiq.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

DEBUG = True

# Azure and Databricks credentials
AZURE_ACCOUNT_NAME = config('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = config('AZURE_ACCOUNT_KEY')
AZURE_FILE_SYSTEM = config('AZURE_FILE_SYSTEM')
DATABRICKS_HOST = config('DATABRICKS_HOST')
DATABRICKS_TOKEN = config('DATABRICKS_TOKEN')
DATABRICKS_CLUSTER_ID = config('DATABRICKS_CLUSTER_ID')
# Databricks settings
DATABRICKS_HOST = 'https://adb-3623933893880845.5.azuredatabricks.net'
DATABRICKS_TOKEN = 'dapi44c5e998d105e25008af210c77e37f3a-3'
DATABRICKS_HTTP_PATH = '/sql/1.0/warehouses/50e55df2f9229a9e'
DATABRICKS_DASHBOARD_ID = '01f031711a751af7876b9008149aa390'  # your dashboard id
DATABRICKS_WORKSPACE_URL = 'https://adb-3623933893880845.5.azuredatabricks.net'  # your workspace URL

# Temporary file storage
TEMP_DIR = BASE_DIR / 'temp'
SECRET_KEY = 'mhot9pl*(mz1pc$@xve9qn%v2ogy6cj%-$5wrha0#(4#rlu_6v'